# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\GUOBAJUN\Documents\文稿\Education\2023春季\网络系统\ComputerManageSystem\Client\UI\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Mainwindow(object):
    def setupUi(self, Mainwindow):
        Mainwindow.setObjectName("Mainwindow")
        Mainwindow.resize(456, 115)
        self.Port_TextEdit = PlainTextEdit(Mainwindow)
        self.Port_TextEdit.setEnabled(False)
        self.Port_TextEdit.setGeometry(QtCore.QRect(280, 40, 80, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Port_TextEdit.setFont(font)
        self.Port_TextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Port_TextEdit.setObjectName("Port_TextEdit")
        self.Addr_Label = QtWidgets.QLabel(Mainwindow)
        self.Addr_Label.setGeometry(QtCore.QRect(0, 40, 81, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Addr_Label.setFont(font)
        self.Addr_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Addr_Label.setObjectName("Addr_Label")
        self.Port_Label = QtWidgets.QLabel(Mainwindow)
        self.Port_Label.setGeometry(QtCore.QRect(220, 40, 51, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Port_Label.setFont(font)
        self.Port_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Port_Label.setObjectName("Port_Label")
        self.label_3 = QtWidgets.QLabel(Mainwindow)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 191, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Edit_Btn = PrimaryToolButton(Mainwindow)
        self.Edit_Btn.setGeometry(QtCore.QRect(370, 40, 70, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Edit_Btn.setFont(font)
        self.Edit_Btn.setObjectName("Edit_Btn")
        self.Addr_TextEdit = PlainTextEdit(Mainwindow)
        self.Addr_TextEdit.setEnabled(False)
        self.Addr_TextEdit.setGeometry(QtCore.QRect(80, 40, 131, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Addr_TextEdit.setFont(font)
        self.Addr_TextEdit.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Addr_TextEdit.setObjectName("Addr_TextEdit")
        self.Status_Label = QtWidgets.QLabel(Mainwindow)
        self.Status_Label.setGeometry(QtCore.QRect(200, 70, 90, 32))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Status_Label.setFont(font)
        self.Status_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Status_Label.setObjectName("Status_Label")

        self.retranslateUi(Mainwindow)
        QtCore.QMetaObject.connectSlotsByName(Mainwindow)

    def retranslateUi(self, Mainwindow):
        _translate = QtCore.QCoreApplication.translate
        Mainwindow.setWindowTitle(_translate("Mainwindow", "Mainwindow"))
        self.Port_TextEdit.setPlaceholderText(_translate("Mainwindow", "10086"))
        self.Addr_Label.setText(_translate("Mainwindow", "主机地址"))
        self.Port_Label.setText(_translate("Mainwindow", "端口"))
        self.label_3.setText(_translate("Mainwindow", "客户端代理运行状况"))
        self.Edit_Btn.setText(_translate("Mainwindow", "编辑"))
        self.Addr_TextEdit.setPlaceholderText(_translate("Mainwindow", "127.0.0.1"))
        self.Status_Label.setText(_translate("Mainwindow", "正常"))
from qfluentwidgets import PlainTextEdit, PrimaryToolButton
