FROM python:3.10

RUN mkdir /Client
WORKDIR /Client

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U

ADD requirements_cli_win.txt /Client/

RUN pip install -r requirements_cli_win.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

ADD . /Client/

CMD [ "python3","AgentCLI.py" ]
